# Generated by Django 3.2.12 on 2024-04-15 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('material', models.CharField(max_length=255)),
                ('sizes', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Machines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('year_of_release', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Masters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('qualification', models.CharField(max_length=255)),
                ('work_experience', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('client', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PartsManufacturing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_end', models.DateField()),
                ('quantity', models.IntegerField()),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pp02_app.details')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pp02_app.machines')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pp02_app.masters')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pp02_app.orders')),
            ],
        ),
    ]
